# -*- coding: utf-8 -*-
"""us-accidents-analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pm2VQGKIYZebNp92Sb8EKgCmm_-ksb-M
"""

# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!zpip install jovian --upgrade -q
import jovian
jovian.set_project('us-accidents-analysis')
jovian.set_colab_id('1Pm2VQGKIYZebNp92Sb8EKgCmm_-ksb-M')

"""#US ACCIDENT EXPLORATERY DATA Analysis 

TODO- talk about EDA
TODO- talk about the datasets (source,what it contains, how it will be usefull)
  - Kaggle
  - information about accidents
  - Can be useful to prevent accodents
  - Mention that this does not contain data about New York
"""

pip install opendatasets --upgrade

import opendatasets as od

download_url='https://www.kaggle.com/sobhanmoosavi/us-accidents'

od.download(download_url)

data_filename='./us-accidents/US_Accidents_Dec20_Updated.csv'

"""##Data Prepration and Cleaning

- load the file using Pandas
- Look at some information about the file data and the colukmns
- Fix any missing or incorrect values

"""

import pandas as pd

df = pd.read_csv(data_filename)

df

df.columns

df.info()

df.describe()

numerics = ['int16','int32','int64','float16','float32','float64']

numeric_df = df.select_dtypes(include=numerics)

len(numeric_df.columns)

df.isna()

"""Percentage of finding missing values per column"""

df.isna().sum()

missing_percentages = df.isna().sum().sort_values(ascending=False)/len(df)
missing_percentages

type(missing_percentages)

missing_percentages!=0

missing_percentages[missing_percentages!=0]

missing_percentages[missing_percentages!=0].plot(kind='barh')

"""Remove columns That you don't want to use.

##Exploratory Analysis and Visulization

columns we'll analyze:

  1. City
  2. Start Time
  3. Start Lat, Start Lang
  4. Tempreture
  5. Weather conditions

###    1. City
"""

df.columns

df.City

cities = df.City.unique()

len(cities)

cities[:100]

cities_by_accident = df.City.value_counts()
cities_by_accident

type(cities_by_accident)

'New York' in df.City

cities_by_accident[:20].plot(kind='barh')

import seaborn as sns
sns.set_style('darkgrid')

sns.histplot(cities_by_accident,log_scale=True)

high_accident_cities=cities_by_accident[cities_by_accident>=1000]
low_accident_cities=cities_by_accident[cities_by_accident<1000]

len(high_accident_cities)

len(high_accident_cities)/len(cities)

sns.histplot(high_accident_cities,log_scale=True)

cities_by_accident[cities_by_accident==1]

sns.histplot(low_accident_cities,log_scale=True)

"""###    2. Start Time"""

df.Start_Time

df.Start_Time=pd.to_datetime(df.Start_Time)

df.Start_Time[0]

sns.displot(df.Start_Time.dt.hour,bins=24,kde=False)

"""- A high percentage of accidents occur between 7 am to 9am [probabely people would be in hurry to getr to work]
- Next highest percentage is 3 pm to 6pm
"""

sns.displot(df.Start_Time.dt.dayofweek,bins=7,kde=False)

"""- A high rate of accident is noted on week days [since there will be much more buzzz around the city]
- And in Weekends there is a less accidents rate [since most people will be in home enjoying there Weakend]

Is the distribution by hour the same on weekends as on weekdays...?
"""

sundays_start_time=df.Start_Time[df.Start_Time.dt.day==6]
sns.displot(sundays_start_time.dt.hour,bins=24,kde=False)

mondays_start_time=df.Start_Time[df.Start_Time.dt.dayofweek==0]
sns.displot(mondays_start_time.dt.hour,bins=24,kde=False)

"""On sundays, the peak occurance is betweem 10 am and 3pm, unlike weekdays."""

sns.displot(mondays_start_time.dt.month,bins=12,kde=False)

df_2016=df[df.Start_Time.dt.year==2016]
sns.displot(df_2016.Start_Time.dt.month,bins=12,kde=False)

df_2017=df[df.Start_Time.dt.year==2017]
sns.displot(df_2017.Start_Time.dt.month,bins=12,kde=False)

df_2018=df[df.Start_Time.dt.year==2018]
sns.displot(df_2018.Start_Time.dt.month,bins=12,kde=False)

df_2019=df[df.Start_Time.dt.year==2019]
sns.displot(df_2019.Start_Time.dt.month,bins=12,kde=False)

df_2020=df[df.Start_Time.dt.year==2020]
sns.displot(df_2020.Start_Time.dt.month,bins=12,kde=False)

"""- High rate of accident has occured from Augest to December [This may be because of change of weather from summer to winter, According to road safety experts, low visibility, long night hours and increased use of four-wheelers during winter]
- This Data set contains data from February So there is some amount of data loss in the month of January so the plot has some inconsistincies.

- But when we look year by year data the plot is preeaty balanced so there might be inappropriate amount of data in starting of the year.

##   3.Start Latitud and Longititude
"""

df.Start_Lat

df.Start_Lng

sns.scatterplot(x=df.Start_Lng,y=df.Start_Lat)

sample_df = df.sample(int(0.1*len(df)))

sns.scatterplot(x=sample_df.Start_Lng,y=sample_df.Start_Lat,size=0.001)

import folium

lat, lon = df.Start_Lat[0] , df.Start_Lng[0]
lat , lon

list(zip(list(df.Start_Lat), list(df.Start_Lng)))

from folium.plugins import HeatMap

Sample_df=df.sample(int(0.01*len(df)))
lat_lon_pairs=list(zip(list(Sample_df.Start_Lat),list(Sample_df.Start_Lng)))

map=folium.Map()
HeatMap(lat_lon_pairs).add_to(map)
map

"""##Ask & Answer Questions
    1. Are there more accidents in warmer or colder areas?
    2. which states has the higest number of accidents?
    3. Does New York show up in the data? If yes,why is the count lower if this the most populated city.
    4. Among the top 100 cities in number of accidents, which states do they belong to most frequently.
    5. What Time of the day are accidents most freqiuent in?
    6. Which days of the week have the most accidents?
    7. Which month have the most accidents?
    8. What is the Trend of accidents year-over-year (decreasing/increasing)?

1. This data cannot be dwawn proprly
2. Los Angeles 
3. NO, New York has not bee added to the dataset
4. Los Angeles and Houston
5. - A high percentage of accidents occur between 7 am to 9am [probabely people would be in hurry to getr to work]
  - Next highest percentage is 3 pm to 6pm
6. - A high rate of accident is noted on week days [since there will be much more buzzz around the city]
  - And in Weekends there is a less accidents rate [since most people will be in home enjoying there Weakend]
7. December
8. - High rate of accident has occured from Augest to December [This may be because of change of weather from summer to winter, According to road safety experts, low visibility, long night hours and increased use of four-wheelers during winter]

  - This Data set contains data from February So there is some amount of data loss in the month of January so the plot has some inconsistincies.

  - But when we look year by year data the plot is preeaty balanced so there might be inappropriate amount of data in starting of the year.

## Summery and Conclusion

Insights:
- No data from New York
- The number of accidents per city Decreases/Increasses Exponentially.
- Less then 5% of cities have more than 1000 yearly accidents
- Over 1300 cities have reported just one accident(need to investigate)
- This data Set is not been compiled completly and there are data in consistinces.
"""